name: swaps

on: ["push", "pull_request"]

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  unitary:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        decimals: [18]
        return_type: ["revert"]
        plain_pool_type: ["basic", "eth", "optimized", "rebase"]
        pool_size: [2, 3, 4]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
            ~/.brownie
            /home/runner/work/kagla-factory/build
          key: compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Ganache
        run: npm install

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: brownie test tests/pools --decimals ${{ matrix.decimals }} --return-type ${{ matrix.return_type }} --pool-type ${{ matrix.plain_pool_type }} --plain-pool-size ${{ matrix.pool_size }}  --cache-clear
